// front_end-frameworks/vue/src/components/ui/Brand.vue
<script setup>
import { computed } from "vue";
import { BrainCircuit } from "lucide-vue-next";

const props = defineProps({
  // Fourni : la marque devient un lien. Absent : un simple conteneur.
  href: { type: String, default: undefined },
  // "lg" pour le header, "sm" pour le footer.
  size: { type: String, default: "sm" },
});

const isLarge = computed(() => props.size === "lg");
</script>

<template>
  <!-- <component :is> remplace l'idiome React `const Wrapper = href ? "a" : "div"` -->
  <component
    :is="href ? 'a' : 'div'"
    :href="href"
    class="flex items-center gap-2"
  >
    <div
      :class="[
        'flex items-center justify-center rounded-lg bg-violet-500 text-slate-50 shadow-lg shadow-violet-500/40',
        isLarge ? 'p-2' : 'h-7 w-7',
      ]"
    >
      <BrainCircuit :size="16" />
    </div>

    <span :class="['text-slate-50', isLarge ? 'text-xl' : 'text-sm font-bold']">
      Agentic AI
    </span>
  </component>
</template>

// front_end-frameworks/react/src/components/ui/Brand.jsx
import { BrainCircuit } from "lucide-react";

/**
 * Le logo « Agentic AI », partagé par le header et le footer.
 *
 * - `size` : "lg" pour le header, "sm" (défaut) pour le footer.
 * - `href` : optionnel. Fourni, la marque devient un lien cliquable ;
 *   absent, un simple conteneur.
 */
function Brand({ href, size = "sm", className = "" }) {
  const isLarge = size === "lg";

  // Le nom de balise est une variable : JSX résout `Wrapper` (majuscule)
  // vers son contenu, ici la chaîne "a" ou "div" — donc une balise HTML.
  const Wrapper = href ? "a" : "div";

  return (
    <Wrapper href={href} className={`flex items-center gap-2 ${className}`}>
      <div
        className={`flex items-center justify-center rounded-lg bg-violet-500 text-slate-50 shadow-lg shadow-violet-500/40 ${
          isLarge ? "p-2" : "h-7 w-7"
        }`}
      >
        <BrainCircuit size={16} />
      </div>

      <span
        className={`text-slate-50 ${isLarge ? "text-xl" : "text-sm font-bold"}`}
      >
        Agentic AI
      </span>
    </Wrapper>
  );
}

export default Brand;
