// front_end-frameworks/vue/src/components/ui/SectionBadge.vue
<!--
  Le badge violet en tete de chaque section.

  Pas de prop `class` : Vue fusionne automatiquement le `class` pose par
  l'appelant avec celui de l'element racine (fallthrough attributes).
-->
<template>
  <p
    class="inline-flex items-center gap-2 rounded-full border border-violet-500/20 bg-violet-500/10 px-4 py-2 text-xs text-violet-300"
  >
    <span
      aria-hidden="true"
      class="text-[8px]"
    >✦</span>
    <slot />
    <span
      aria-hidden="true"
      class="text-[8px]"
    >✦</span>
  </p>
</template>

// front_end-frameworks/react/src/components/ui/SectionBadge.jsx
/**
 * Le petit badge violet en tête de chaque section.
 *
 * `className` reste à la main de l'appelant : le badge possède les classes
 * de son apparence, pas celles de son placement (marges), qui dépendent
 * de la section où il est posé.
 */
function SectionBadge({ children, className = "" }) {
  return (
    <p
      className={`inline-flex items-center gap-2 rounded-full border border-violet-500/20 bg-violet-500/10 px-4 py-2 text-xs text-violet-300 ${className}`}
    >
      <span aria-hidden="true" className="text-[8px]">
        ✦
      </span>
      {children}
      <span aria-hidden="true" className="text-[8px]">
        ✦
      </span>
    </p>
  );
}

export default SectionBadge;
