// front_end-frameworks/svelte/src/components/sections/Features.svelte
<script>
  import SectionBadge from "../ui/SectionBadge.svelte";
  import SectionTitle from "../ui/SectionTitle.svelte";
  import FeatureCard from "../cards/FeatureCard.svelte";
  import features from "../../data/features.js";
</script>

<section id="features-section" class="bg-black py-24">
  <div class="mx-auto max-w-6xl px-6">
    <!-- En-tête centré -->
    <div class="text-center">
      <!-- Eyebrow -->
      <SectionBadge class="mb-6">Features</SectionBadge>

      <!-- Title -->
      <SectionTitle highlight="With powerful AI agents">
        Everything You Need to Build
      </SectionTitle>
    </div>

    <!-- Features -->
    <div class="mt-12 grid gap-8 md:grid-cols-3">
      {#each features as feature (feature.title)}
        <FeatureCard
          icon={feature.icon}
          title={feature.title}
          description={feature.description}
        />
      {/each}
    </div>
  </div>
</section>

// front_end-frameworks/react/src/components/sections/Features.jsx
import SectionTitle from "../ui/SectionTitle";
import SectionBadge from "../ui/SectionBadge";
import FeatureCard from "../cards/FeatureCard";
import features from "../../data/features";

function Features() {
  return (
    <section id="features-section" className="bg-black py-24">
      <div className="mx-auto max-w-6xl px-6">
        {/* En-tête centré */}
        <div className="text-center">
          {/* Eyebrow */}
          <SectionBadge className="mb-6">Features</SectionBadge>

          {/* Title */}
          <SectionTitle highlight="With powerful AI agents">
            Everything You Need to Build
          </SectionTitle>
        </div>
        {/* Features */}
        <div className="mt-12 grid gap-8 md:grid-cols-3">
          {features.map((feature) => (
            <FeatureCard
              key={feature.title}
              icon={feature.icon}
              title={feature.title}
              description={feature.description}
            />
          ))}
        </div>
      </div>
    </section>
  );
}

export default Features;
