// front_end-frameworks/svelte/src/App.svelte
<script>
  import Header from "./components/layout/Header.svelte";
  import Hero from "./components/sections/Hero.svelte";
  import About from "./components/sections/About.svelte";
  import Features from "./components/sections/Features.svelte";
  import Insights from "./components/sections/Insights.svelte";
  import Contact from "./components/sections/Contact.svelte";
  import Footer from "./components/layout/Footer.svelte";
</script>

<Header />
<Hero />
<About />
<Features />
<Insights />
<Contact />
<Footer />

// front_end-frameworks/react/src/App.jsx
import Header from "./components/Header";
import Hero from "./sections/Hero";
import About from "./sections/About";
import Features from "./sections/Features";
import Insights from "./sections/Insights";
import Contact from "./sections/Contact";
import Footer from "./components/Footer";

function App() {
  return (
    <>
      <Header />
      <Hero />
      <About />
      <Features />
      <Insights />
      <Contact />
      <Footer />
    </>
  );
}

export default App;
