// front_end-frameworks/svelte/src/components/sections/Insights.svelte
<script>
  import { onMount } from "svelte";

  import SectionBadge from "../ui/SectionBadge.svelte";
  import SectionTitle from "../ui/SectionTitle.svelte";
  import InsightCard from "../cards/InsightCard.svelte";
  import getInsights from "../../services/insightsService.js";

  let insights = $state([]);
  let erreur = $state("");

  // onMount remplace useEffect(..., []) : execute une fois, apres l'insertion
  // dans le DOM. Le callback peut etre async directement, ce que React
  // interdisait — d'ou la fonction `charger()` imbriquee dans la version JSX.
  onMount(async () => {
    try {
      insights = await getInsights();
    } catch (error) {
      erreur = "Unable to load the insights.";
      console.error(error);
    }
  });
</script>

<section id="insights-section" class="bg-black py-24">
  <div class="mx-auto max-w-6xl px-6">
    <!-- En-tête centré -->
    <div class="text-center">
      <!-- Eyebrow -->
      <SectionBadge class="mb-6">Insights</SectionBadge>

      <!-- Title -->
      <SectionTitle highlight="Through real-world scenes">
        Explore Agentic AI
      </SectionTitle>
    </div>

    {#if erreur}
      <p class="text-sm text-slate-50">{erreur}</p>
    {/if}

    <!-- Insights -->
    <div class="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
      {#each insights as insight, index (insight.category)}
        <InsightCard
          {index}
          image={insight.image}
          category={insight.category}
          title={insight.title}
          description={insight.description}
        />
      {/each}
    </div>
  </div>
</section>

// front_end-frameworks/react/src/sections/Insights.jsx
import { useState, useEffect } from "react";
import InsightCard from "../components/InsightCard";
import getInsights from "../services/insightsService";


function Insights() {
    const [insights, setInsights] = useState([]);
    const [erreur, setErreur] = useState("");

    useEffect(() => {
        async function charger() {
            try {
                const data = await getInsights();
                setInsights(data);
            } catch (error) {
                setErreur("Unable to load the insights.");
                console.error(error)
            }
        }
        charger();
    }, []);

    return (
        <section id="insights-section" className="bg-black py-24">
      <div className="mx-auto max-w-6xl px-6">
        {/* En-tête centré */}
        <div className="text-center">
          {/* Eyebrow */}
          <p className="mb-6 inline-flex rounded-full border border-violet-500/20 bg-violet-500/10 px-4 py-2 text-xs text-violet-300">
            ♦ Insights ♦
          </p>

          {/* Title */}
          <h2 className="text-4xl leading-none font-black tracking-tight md:text-5xl">
            <span className="block text-slate-50">
              Explore Agentic AI
            </span>
            <span className="block text-violet-300">
              Through real-world scenes
            </span>
          </h2>
        </div>

        {erreur && <p className="text-slate-50 text-sm ">{erreur}</p>}
        {/* Insights */}
        <div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
          {insights.map((insight, index) => (
            <InsightCard
              key={insight.category}
              index={index}
              image={insight.image}
              category={insight.category}
              title={insight.title}
              description={insight.description}
            />
          ))}
        </div>
      </div>
    </section>
    );
}

export default Insights;
